language: php

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:

    -   name: 'PHPUnit with PHP 7.2'
        php: 7.2
        before_script: composer install -n
        script: vendor/bin/phpunit

    -   name: 'PHPUnit with PHP 7.3'
        php: 7.3
        before_script: composer install -n
        script: vendor/bin/phpunit

    -   name: 'PHPUnit with lowest dependencies'
        php: 7.2
        before_script: composer update --prefer-lowest --prefer-stable -n
        script: vendor/bin/phpunit

    -   name: 'PHPStan'
        php: 7.3
        before_script: composer install -n
        script: vendor/bin/phpstan analyse
